# fly.toml app configuration file generated for binify-hash-generator on 2025-12-25T10:44:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'binify-hash-generator'
primary_region = 'ams'

[build]

[env]
  PORT = '8081'

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8081

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '5s'

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
